<a href="https://colab.research.google.com/github/ChristabelEyiah/lab-4-llm-decision-support/blob/main/lab_4_llm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import os

# --- Google Colab (Secrets panel) ---
from google.colab import userdata
API_KEY = userdata.get("GROQ_API_KEY")

# OpenAI-compatible client
from openai import OpenAI

client = OpenAI(
    api_key=API_KEY,
    base_url="https://api.groq.com/openai/v1",
)

MODEL = "llama-3.3-70b-versatile"

print("Client ready.")

Client ready.

In [12]:
def ask_llm(user_prompt, system_prompt="You are a helpful assistant.",
            temperature=0.7, max_tokens=500):
    response = client.chat.completions.create(
        model=MODEL,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ],
        temperature=temperature,
        max_tokens=max_tokens,
    )
    return response


# Test the function
response = ask_llm("What is artificial intelligence?")

print("Answer:")
print(response.choices[0].message.content)

print("\nToken usage:")
print(response.usage)

Answer:
Artificial intelligence (AI) refers to the development of computer systems that can perform tasks that typically require human intelligence, such as:

1. **Learning**: AI systems can learn from data, experiences, and interactions, allowing them to improve their performance over time.
2. **Problem-solving**: AI systems can analyze problems, identify patterns, and make decisions or take actions to solve them.
3. **Reasoning**: AI systems can draw inferences, make logical connections, and arrive at conclusions based on available data.
4. **Perception**: AI systems can interpret and understand data from sensors, such as images, speech, and text.

AI involves a range of techniques, including:

1. **Machine learning**: AI systems can learn from data using algorithms and statistical models.
2. **Deep learning**: A type of machine learning that uses neural networks to analyze complex data, such as images and speech.
3. **Natural language processing**: AI systems can understand, generate, and process human language.
4. **Computer vision**: AI systems can interpret and understand visual data from images and videos.

AI has many applications, including:

1. **Virtual assistants**: AI-powered assistants, such as Siri, Alexa, and Google Assistant, can perform tasks, answer questions, and provide information.
2. **Image recognition**: AI-powered systems can recognize objects, people, and patterns in images.
3. **Speech recognition**: AI-powered systems can transcribe spoken language into text.
4. **Predictive analytics**: AI-powered systems can analyze data to make predictions and forecasts.
5. **Autonomous vehicles**: AI-powered systems can control and navigate self-driving cars.

The goals of AI research include:

1. **Creating intelligent machines**: Developing machines that can think, learn, and act like humans.
2. **Improving decision-making**: Using AI to analyze data and make informed decisions.
3. **Enhancing human capabilities**: Using AI to augment human abilities, such as memory, attention, and cognition.

Overall, artificial intelligence has the potential to revolutionize many aspects of our lives, from healthcare and education to transportation and entertainment.

Token usage:
CompletionUsage(completion_tokens=426, prompt_tokens=46, total_tokens=472, completion_tokens_details=None, prompt_tokens_details=None, queue_time=0.064960952, prompt_time=0.004184291, completion_time=0.861879485, total_time=0.866063776)

**Student Reasoning - Anatomy of A Call**

1. What is the difference between the system and user roles?

The system role gives the LLM general instructions about how it should behave or respond. It sets the context, rules, or personality for the conversation. The user role contains the actual question or task that the user wants the LLM to answer.

2. What is a token, roughly? Why do API providers bill per token rather than per request?

A token is a small piece of text that an LLM processes. It can be a whole word, part of a word, punctuation, or another small unit of text.

API providers bill based on tokens because the amount of computation required depends largely on how much text the model has to process and generate, not simply on the number of API requests. A short request might use only a few tokens, while a long conversation or response could use thousands. Charging per token therefore more accurately reflects the resources used by the model.

In [14]:
question = "Suggest a name for a savings product for market traders in Accra."

# Temperature = 0.0
print("TEMPERATURE 0.0")

for i in range(5):
    response = ask_llm(
        question,
        temperature=0.0,
        max_tokens=100
    )
    print(f"\nAnswer {i+1}:")
    print(response.choices[0].message.content)


# Temperature = 1.2
print("\n\nTEMPERATURE 1.2 ")

for i in range(5):
    response = ask_llm(
        question,
        temperature=1.2,
        max_tokens=100
    )
    print(f"\nAnswer {i+1}:")
    print(response.choices[0].message.content)

TEMPERATURE 0.0

Answer 1:
Here are a few suggestions for a savings product for market traders in Accra:

1. **Makola Save**: "Makola" is a well-known market in Accra, so this name could resonate with market traders.
2. **Trader's Treasure**: This name emphasizes the idea of saving and accumulating wealth, which could appeal to market traders.
3. **Sika Souce**: "Sika" means "money" in the Akan language, which is widely spoken in Ghana

Answer 2:
Here are a few suggestions for a savings product for market traders in Accra:

1. **Makola Save**: "Makola" is a well-known market in Accra, so this name could resonate with market traders.
2. **Trader's Treasure**: This name emphasizes the idea of saving and accumulating wealth, which could appeal to market traders.
3. **Sika Souce**: "Sika" means "money" in the Akan language, which is widely spoken in Ghana

Answer 3:
Here are a few suggestions for a savings product for market traders in Accra:

1. **Makola Save**: "Makola" is a well-known market in Accra, so this name could resonate with market traders.
2. **Trader's Treasure**: This name emphasizes the idea of saving and accumulating wealth.
3. **Accra Amanfu**: "Amanfu" is a Ghanaian word for "savings" or "treasury", so this name incorporates local language

Answer 4:
Here are a few suggestions for a savings product for market traders in Accra:

1. **Makola Save**: "Makola" is a well-known market in Accra, so this name could resonate with market traders.
2. **Trader's Treasure**: This name emphasizes the idea of saving and accumulating wealth.
3. **Accra Amanfu**: "Amanfu" is a Ghanaian word for "savings" or "treasury", which could appeal to market traders

Answer 5:
Here are a few suggestions for a savings product for market traders in Accra:

1. **Makola Save**: "Makola" is a well-known market in Accra, so this name could resonate with market traders.
2. **Trader's Treasure**: This name emphasizes the idea of saving and accumulating wealth.
3. **Accra Amanfu**: "Amanfu" is a Ghanaian word for "savings" or "treasury", so this name incorporates local language


TEMPERATURE 1.2

Answer 1:
Here are some suggestions for a savings product tailored to market traders in Accra:

1. **Makola Save**: "Makola" is a reference to the famous Makola Market in Accra, making it a relatable and relevant name for market traders.
2. **TradeSafe**: This name conveys the idea of securely saving for the future, which is essential for market traders who often face uncertain income.
3. **MarketBoost**: This name suggests that the savings product will help

Answer 2:
What a great idea for a savings product. Here are a few name suggestions for a savings product tailored to market traders in Accra:

1. **MakolaSave**: "Makola" is a well-known market in Accra, so this name immediately conveys that the product is designed for market traders.
2. **TraderCare**: This name emphasizes the supportive nature of the savings product, conveying that it's designed to help traders care for their financial well-being.
3. **Acc

Answer 3:
For a savings product tailored to market traders in Accra, here are a few suggestions:

1. **Makola Savings**: "Makola" is a well-known market in Accra, so this name could resonate with traders.
2. **Traders' Treasure**: This name emphasizes the idea of saving and growing one's wealth.
3. **Sika Kokoo**: "Sika" means "money" in the Akan language, and "Kokoo" means "gather

Answer 4:
Here are a few suggestions for a savings product for market traders in Accra:

1. **Makola Saver**: "Makola" is a well-known market in Accra, and this name could resonate with market traders.
2. **Traders' Treasure**: This name conveys the idea of saving money as a valuable treasure, which could appeal to market traders.
3. **Abi Saver**: "Abi" is a Ghanaian word that means "until" or

Answer 5:
Considering the target market and the product's purpose, here are a few suggestions for a savings product name for market traders in Accra:

1. **Makola Savings**: "Makola" is a well-known market in Accra, and using this name could help create a sense of familiarity and connection with the target market.
2. **Trader's Vault**: This name emphasizes the idea of a secure and safe place to store savings, which is reassuring for market traders who often handle cash.

**Student Reasoning - Temperature**
At temperature 0.0, the responses were generally more consistent and similar to each other. The model tended to give the same or very similar suggestions because there is less randomness in the generation process.

At temperature 1.2, the responses were more varied and creative. The model produced a wider range of possible names, but the results were also less predictable.

For the loan decision-support system, a low temperature such as 0.0 or around 0.2–0.3 is more appropriate. Loan decisions should be consistent, predictable, and based on the information provided rather than creative or random responses. A low temperature reduces unnecessary variation and makes the system more reliable when providing explanations or recommendations.

In [15]:
LETTERS = {
"L001": """Dear Sir/Madam,
My name is Akosua Mensah and I have been selling provisions at Makola Market for 12 years.
I am applying for a loan of GHS 8,000 to buy a deep freezer and expand into frozen foods.
My current stall makes about GHS 900 profit each month. I have saved GHS 2,500 with your
susu scheme over the past two years and I have never missed a contribution. I can repay
GHS 450 monthly over 20 months. My sister, a teacher, will stand as my guarantor.
Thank you for considering my application.""",

"L002": """Hello,
I am Kwame Boateng, a commercial driver in Kumasi. I need GHS 25,000 urgently to repair my
trotro engine and settle some personal debts. Business has been slow but it will surely
pick up after the festive season. I can pay back whenever the money comes. I do not have
collateral at the moment but God willing everything will be fine. Please help me quickly.""",

"L003": """Dear Loan Committee,
I am Efua Darko, owner of Darko Fashions, a registered dressmaking business in Takoradi
(registration no. BN-2019-4482). I employ three apprentices. I request GHS 15,000 to
purchase two industrial sewing machines and fabric stock ahead of the Christmas season.
Last year my December revenue alone was GHS 22,000; monthly profit averages GHS 2,800.
I hold a fixed deposit of GHS 5,000 with GCB which I can pledge. Proposed repayment:
GHS 1,100 monthly for 15 months. Attached are my sales records for the past 18 months.""",

"L004": """Good day,
My name is Yaw Owusu. I want a loan for my poultry farm at Nsawam. The amount is GHS 12,000
for feed and 500 new layers. I started the farm last year. Sometimes I make good money,
around GHS 1,500 in a good month, but bird flu affected us in March and I lost many birds.
I am rebuilding now. I can repay in 18 months. My uncle has agreed to guarantee the loan
with his taxi.""",

"L005": """Dear Manager,
I am writing on behalf of the Adenta Women's Weaving Cooperative (14 members). We seek
GHS 30,000 to buy a bulk order of yarn directly from the factory, cutting out middlemen and
raising our margins from 15% to about 35%. The cooperative has operated for 6 years and
holds GHS 9,000 in our group account. We propose repayment of GHS 2,000 monthly over
16 months, backed by our group savings and joint liability agreement.""",

"L006": """Hi,
This is Kofi. I saw your advert. I want GHS 50,000 to start a car washing business, a
provision shop, and also import phones from Dubai. I am 22 and full of energy. I have not
started any of these yet but my friends say I am very business minded. I will pay back in
one year when the businesses are booming. No collateral but I am trustworthy.""",
}

# Gold-standard labels for three letters (for Section 4 evaluation):
GOLD = {
  "L001": {"applicant_name": "Akosua Mensah", "amount_ghs": 8000,  "purpose": "buy deep freezer / expand into frozen foods",
           "monthly_profit_ghs": 900,  "has_collateral_or_guarantor": True,  "repayment_months": 20},
  "L003": {"applicant_name": "Efua Darko",    "amount_ghs": 15000, "purpose": "industrial sewing machines and fabric stock",
           "monthly_profit_ghs": 2800, "has_collateral_or_guarantor": True,  "repayment_months": 15},
  "L006": {"applicant_name": "Kofi",          "amount_ghs": 50000, "purpose": "car wash, provision shop, phone imports",
           "monthly_profit_ghs": None, "has_collateral_or_guarantor": False, "repayment_months": 12},
}

print(f"{len(LETTERS)} letters loaded.")

6 letters loaded.

In [ ]:
# first attempt
SUMMARY_PROMPT_V1 = "Summarize this:"

for letter_id in ["L002", "L006"]:
    print(f"\n===== {letter_id} — V1 =====")

    response = ask_llm(
        f"{SUMMARY_PROMPT_V1}\n\n{LETTERS[letter_id]}",
        temperature=0.7,
        max_tokens=200
    )

    print(response.choices[0].message.content)

===== L002 — V1 =====
Kwame Boateng, a commercial driver in Kumasi, is requesting GHS 25,000 to repair his vehicle's engine and pay off personal debts. He's struggling due to slow business, but expects it to improve after the festive season. He has no collateral to offer, but promises to repay the loan as soon as possible.

===== L006 — V1 =====
Kofi, a 22-year-old, is seeking a loan of GHS 50,000 to start three businesses: a car washing service, a provision shop, and a phone import business from Dubai. He has no prior experience, but claims to be "business-minded" based on his friends' opinion. He promises to repay the loan within one year, once his businesses are successful, and is offering his trustworthiness as assurance, as he has no collateral to offer.

In [16]:
# SUMMARY_PROMPT_V2

SUMMARY_SYSTEM_V2 = """You are an assistant to a microfinance loan officer.
Summarize loan application letters into a brief factual summary.
Be neutral and objective. Do not invent, assume, or infer information that is
not explicitly stated in the letter. Include the applicant, requested loan
amount, purpose of the loan, business/financial situation, and repayment or
security information when available. Keep the summary to 3-4 sentences."""

SUMMARY_PROMPT_V2 = """Summarize this loan application:

{letter_text}"""

In [17]:
for letter_id in ["L002", "L006"]:
    print(f"\n===== {letter_id} — V2 =====")

    user_prompt = SUMMARY_PROMPT_V2.format(
        letter_text=LETTERS[letter_id]
    )

    response = ask_llm(
        user_prompt,
        system_prompt=SUMMARY_SYSTEM_V2,
        temperature=0.0,
        max_tokens=200
    )

    print(response.choices[0].message.content)

===== L002 — V2 =====
Kwame Boateng, a commercial driver in Kumasi, is applying for a loan of GHS 25,000. The purpose of the loan is to repair his trotro engine and settle personal debts. His business has been slow, but he expects it to improve after the festive season. Kwame does not have collateral to offer, but is hopeful of repaying the loan as his finances improve.

===== L006 — V2 =====
Kofi is applying for a loan of GHS 50,000 to start three businesses: a car washing business, a provision shop, and a phone import business. He is 22 years old and has not yet started any of these ventures. Kofi plans to repay the loan in one year, expecting his businesses to be successful by then. He does not have collateral to offer, but claims to be trustworthy.

**Student Reasoning — Summarization Prompts**

1. What concrete problems did V1's output have that V2 fixed? Quote examples.

V1 was too general because the prompt only said “Summarize this”, so the model was not given specific requirements about what information to prioritize. For example, V1 may have produced a general description of the applicant's situation while leaving out important loan details such as the requested amount, purpose, repayment plan, or lack of collateral. V2 fixed this by explicitly instructing the model to include the applicant, loan amount, purpose, financial situation, and repayment/security information.

2. Why is “no invented details” an essential instruction in this application? What is this failure mode called in the LLM literature?

“No invented details” is essential because this is a loan decision-support system, where inaccurate information could influence whether someone receives a loan. The LLM must only use facts stated in the application and should not assume that an applicant has income, collateral, repayment ability, or other qualifications that were not provided. Inventing information could therefore lead to unfair or financially harmful decisions.

This failure mode is called hallucination in the LLM literature. A hallucination occurs when a model generates information that is unsupported by, or inconsistent with, the provided source.

In [21]:
EXTRACT_PROMPT = """
Extract the required loan application information from the letter below.

Return ONLY a valid JSON object. Do not include markdown, explanations,
comments, or any text outside the JSON object.

The JSON object MUST contain EXACTLY these keys:

{{
  "applicant_name": "string",
  "amount_ghs": "number",
  "purpose": "string",
  "monthly_profit_ghs": "number or null",
  "has_collateral_or_guarantor": "boolean",
  "repayment_months": "number or null"
}}

Rules:
- applicant_name must be the applicant's name as stated in the letter.
- amount_ghs must be the requested loan amount in Ghana cedis.
- purpose must describe what the applicant says the loan will be used for.
- monthly_profit_ghs must be the stated monthly profit, or null if it is not stated.
- has_collateral_or_guarantor must be true if the letter states that the applicant
  has collateral or a guarantor, and false if neither is stated.
- repayment_months must be the stated repayment period in months, or null if it
  is not stated.
- If a field is not stated in the letter, use null. Do not guess.
- Use numbers for numerical values, not strings.
- Use true or false for the boolean field.

Worked example:

Letter:
"My name is Ama Osei. I run a small bakery in Accra. I am requesting
GHS 6,000 to buy an oven. My business makes GHS 1,200 profit per month.
I will repay the loan over 10 months. My brother will guarantee the loan."

Correct JSON:
{{
  "applicant_name": "Ama Osei",
  "amount_ghs": 6000,
  "purpose": "buy an oven",
  "monthly_profit_ghs": 1200,
  "has_collateral_or_guarantor": true,
  "repayment_months": 10
}}

Now extract the information from this loan application:

{letter_text}
"""

In [22]:
import json

def extract_fields(letter_text):
    prompt = EXTRACT_PROMPT.format(letter_text=letter_text)

    try:
        response = ask_llm(
            prompt,
            temperature=0,
            max_tokens=300
        )

        result = response.choices[0].message.content.strip()

        # Remove markdown JSON fences if the model adds them
        if result.startswith("```json"):
            result = result[len("```json"):].strip()

        if result.startswith("```"):
            result = result[len("```"):].strip()

        if result.endswith("```"):
            result = result[:-3].strip()

        # Convert JSON string into Python dictionary
        data = json.loads(result)

        return data

    except json.JSONDecodeError:
        print("Warning: Model returned invalid JSON.")
        return None

    except Exception as e:
        print(f"Warning: Extraction failed: {e}")
        return None

In [23]:
test_result = extract_fields(LETTERS["L001"])

print(test_result)

{'applicant_name': 'Akosua Mensah', 'amount_ghs': 8000, 'purpose': 'buy a deep freezer and expand into frozen foods', 'monthly_profit_ghs': 900, 'has_collateral_or_guarantor': True, 'repayment_months': 20}

In [24]:
results = []

for letter_id, letter_text in LETTERS.items():
    extracted = extract_fields(letter_text)

    if extracted is not None:
        extracted["letter_id"] = letter_id
        results.append(extracted)

print(f"Successfully extracted {len(results)} of {len(LETTERS)} letters.")

Successfully extracted 6 of 6 letters.

In [25]:
import pandas as pd

df = pd.DataFrame(results)

# Put letter_id first
columns = [
    "letter_id",
    "applicant_name",
    "amount_ghs",
    "purpose",
    "monthly_profit_ghs",
    "has_collateral_or_guarantor",
    "repayment_months"
]

df = df[columns]

display(df)

,letter_id,applicant_name,amount_ghs,purpose,monthly_profit_ghs,has_collateral_or_guarantor,repayment_months
0,L001,Akosua Mensah,8000,buy a deep freezer and expand into frozen foods,900.0,True,20.0
1,L002,Kwame Boateng,25000,repair my trotro engine and settle some person...,NaN,False,NaN
2,L003,Efua Darko,15000,purchase two industrial sewing machines and fa...,2800.0,True,15.0
3,L004,Yaw Owusu,12000,for feed and 500 new layers,1500.0,True,18.0
4,L005,Adenta Women's Weaving Cooperative,30000,buy a bulk order of yarn directly from the fac...,NaN,True,16.0
5,L006,Kofi,50000,"start a car washing business, a provision shop...",NaN,False,12.0

**Student Reasoning — Decision Support**

1. Compare the briefs for L003 (strong application) and L006 (weak application). Did the system identify the right strengths and red flags in each?

Yes. The system identified important differences between the two applications. L003 is a stronger application because Efua Darko has an established registered business, employs three apprentices, earns an average monthly profit of GHS 2,800, has a GHS 5,000 fixed deposit that can be pledged, and provides a specific repayment plan of GHS 1,100 monthly for 15 months. These details provide evidence of an operating business, income, and security for the loan.

In contrast, L006 has several red flags. Kofi is requesting GHS 50,000 to start three different businesses that have not yet been established. He does not provide an existing business income or monthly profit, has no collateral, and gives a vague repayment plan based on the businesses "booming." The system therefore correctly identified L003's stronger financial evidence and security while highlighting L006's lack of established income, collateral, and concrete repayment capacity.

2. Why did we forbid the model from outputting "approve"/"reject"? Give one practical and one ethical reason.

Practically, the LLM may make mistakes or misunderstand information in the application, so allowing it to directly approve or reject loans could lead to incorrect financial decisions. The system should instead provide factual information and risk indicators that a qualified human can review.

Ethically, lending decisions can have a significant impact on people's lives and financial opportunities. Allowing an AI to make the final decision could create unfair or biased outcomes without sufficient human oversight or accountability. Keeping the model as a decision-support tool ensures that a human remains responsible for the final lending decision.

In [26]:
fields = [
    "applicant_name",
    "amount_ghs",
    "purpose",
    "monthly_profit_ghs",
    "has_collateral_or_guarantor",
    "repayment_months"
]

# Make letter_id the index for easy lookup
df_eval = df.set_index("letter_id")

rows = []

for field in fields:
    row = {"field": field}
    correct = 0

    for letter_id in GOLD.keys():
        predicted = df_eval.loc[letter_id, field]
        gold_value = GOLD[letter_id][field]

        # Case-insensitive comparison for names
        if field == "applicant_name":
            match = (
                str(predicted).strip().lower()
                == str(gold_value).strip().lower()
            )

        # Exact comparison for numbers, booleans, and null
        else:
            match = predicted == gold_value

        row[letter_id] = "✓" if match else "✗"

        if match:
            correct += 1

    row["accuracy"] = correct / len(GOLD)
    rows.append(row)

accuracy_df = pd.DataFrame(rows)

display(accuracy_df)

                         field L001 L003 L006  accuracy
0               applicant_name    ✓    ✓    ✓  1.000000
1                   amount_ghs    ✓    ✓    ✓  1.000000
2                      purpose    ✗    ✗    ✗  0.000000
3           monthly_profit_ghs    ✓    ✓    ✗  0.666667
4  has_collateral_or_guarantor    ✓    ✓    ✓  1.000000
5             repayment_months    ✓    ✓    ✓  1.000000

In [27]:
import json

def extract_fields(letter_text, temperature=0):
    prompt = EXTRACT_PROMPT.format(letter_text=letter_text)

    try:
        response = ask_llm(
            prompt,
            temperature=temperature,
            max_tokens=300
        )

        result = response.choices[0].message.content.strip()

        # Remove markdown JSON fences if the model adds them
        if result.startswith("```json"):
            result = result[len("```json"):].strip()

        if result.startswith("```"):
            result = result[len("```"):].strip()

        if result.endswith("```"):
            result = result[:-3].strip()

        data = json.loads(result)

        return data

    except json.JSONDecodeError:
        print("Warning: Model returned invalid JSON.")
        return None

    except Exception as e:
        print(f"Warning: Extraction failed: {e}")
        return None

In [28]:
import json

letter = LETTERS["L004"]

results_temp_0 = []
results_temp_1 = []

# Temperature 0.0 — 5 runs
for i in range(5):
    result = extract_fields(letter, temperature=0.0)
    results_temp_0.append(result)

# Temperature 1.0 — 5 runs
for i in range(5):
    result = extract_fields(letter, temperature=1.0)
    results_temp_1.append(result)

In [29]:
def reliability_report(results):
    # Keep only valid JSON results
    valid_results = [r for r in results if r is not None]

    # Convert dictionaries to standardized JSON strings
    unique_results = set(
        json.dumps(r, sort_keys=True)
        for r in valid_results
    )

    return {
        "total_runs": len(results),
        "valid_json": len(valid_results),
        "unique_valid_results": len(unique_results),
        "identical_across_all_valid_runs": len(unique_results) == 1
    }


report_0 = reliability_report(results_temp_0)
report_1 = reliability_report(results_temp_1)

print("Temperature 0.0:")
print(report_0)

print("\nTemperature 1.0:")
print(report_1)

Temperature 0.0:
{'total_runs': 5, 'valid_json': 5, 'unique_valid_results': 1, 'identical_across_all_valid_runs': True}

Temperature 1.0:
{'total_runs': 5, 'valid_json': 5, 'unique_valid_results': 1, 'identical_across_all_valid_runs': True}

In [30]:
print("===== TEMPERATURE 0.0 =====")

for i, result in enumerate(results_temp_0, 1):
    print(f"\nRun {i}:")
    print(result)


print("\n\n===== TEMPERATURE 1.0 =====")

for i, result in enumerate(results_temp_1, 1):
    print(f"\nRun {i}:")
    print(result)

===== TEMPERATURE 0.0 =====

Run 1:
{'applicant_name': 'Yaw Owusu', 'amount_ghs': 12000, 'purpose': 'for feed and 500 new layers', 'monthly_profit_ghs': 1500, 'has_collateral_or_guarantor': True, 'repayment_months': 18}

Run 2:
{'applicant_name': 'Yaw Owusu', 'amount_ghs': 12000, 'purpose': 'for feed and 500 new layers', 'monthly_profit_ghs': 1500, 'has_collateral_or_guarantor': True, 'repayment_months': 18}

Run 3:
{'applicant_name': 'Yaw Owusu', 'amount_ghs': 12000, 'purpose': 'for feed and 500 new layers', 'monthly_profit_ghs': 1500, 'has_collateral_or_guarantor': True, 'repayment_months': 18}

Run 4:
{'applicant_name': 'Yaw Owusu', 'amount_ghs': 12000, 'purpose': 'for feed and 500 new layers', 'monthly_profit_ghs': 1500, 'has_collateral_or_guarantor': True, 'repayment_months': 18}

Run 5:
{'applicant_name': 'Yaw Owusu', 'amount_ghs': 12000, 'purpose': 'for feed and 500 new layers', 'monthly_profit_ghs': 1500, 'has_collateral_or_guarantor': True, 'repayment_months': 18}


===== TEMPERATURE 1.0 =====

Run 1:
{'applicant_name': 'Yaw Owusu', 'amount_ghs': 12000, 'purpose': 'for feed and 500 new layers', 'monthly_profit_ghs': 1500, 'has_collateral_or_guarantor': True, 'repayment_months': 18}

Run 2:
{'applicant_name': 'Yaw Owusu', 'amount_ghs': 12000, 'purpose': 'for feed and 500 new layers', 'monthly_profit_ghs': 1500, 'has_collateral_or_guarantor': True, 'repayment_months': 18}

Run 3:
{'applicant_name': 'Yaw Owusu', 'amount_ghs': 12000, 'purpose': 'for feed and 500 new layers', 'monthly_profit_ghs': 1500, 'has_collateral_or_guarantor': True, 'repayment_months': 18}

Run 4:
{'applicant_name': 'Yaw Owusu', 'amount_ghs': 12000, 'purpose': 'for feed and 500 new layers', 'monthly_profit_ghs': 1500, 'has_collateral_or_guarantor': True, 'repayment_months': 18}

Run 5:
{'applicant_name': 'Yaw Owusu', 'amount_ghs': 12000, 'purpose': 'for feed and 500 new layers', 'monthly_profit_ghs': 1500, 'has_collateral_or_guarantor': True, 'repayment_months': 18}

In [37]:
# Test 1 — Asking about a detail that's not in the letter
test1_letter = LETTERS["L004"]
test1_prompt = f"Based ONLY on the following letter, what is the applicant's credit score?\n\nLetter:\n{test1_letter}"

print("="*20 + " TEST 1 OUTPUT " + "="*20)
test1_raw = ask_llm(test1_prompt, temperature=0, max_tokens=200)
test1_response = test1_raw.choices[0].message.content.strip()
print(test1_response)

# Evaluation criteria for Test 1
test1_lowered = test1_response.lower()
test1_passed = any(phrase in test1_lowered for phrase in [
    "not mentioned", "not provided", "does not state", "not specified", "no information", "absent"
]) and not any(char.isdigit() for char in test1_response)

print(f"\nTEST 1 EVALUATION: {'PASS' if test1_passed else 'FAIL'}")
print("="*66 + "\n")


# Test 2 — Feeding irrelevant text into the field extractor
irrelevant_text = (
    "Accra weather report: Expect scattered thunderstorms across the Greater Accra Region today. "
    "High temperatures will reach 28°C with winds from the south-southwest at 15 km/h."
)

print("="*20 + " TEST 2 OUTPUT " + "="*20)
test2_response = extract_fields(irrelevant_text, temperature=0)
print(test2_response)

# Evaluation criteria for Test 2
if test2_response is None:
    test2_passed = True
elif isinstance(test2_response, dict):
    # Check if core fields were left null/None instead of fabricating data
    core_fields = ["applicant_name", "amount_ghs", "monthly_profit_ghs"]
    has_hallucinations = any(
        test2_response.get(field) not in [None, "null", "N/A", "none", ""]
        for field in core_fields
    )
    test2_passed = not has_hallucinations
else:
    test2_passed = False

print(f"\nTEST 2 EVALUATION: {'PASS' if test2_passed else 'FAIL'}")
print("="*66)

==================== TEST 1 OUTPUT ====================
The applicant's credit score is not mentioned in the letter. The letter only provides information about the applicant's loan request, business, and repayment plan, but does not include any details about their credit score.

TEST 1 EVALUATION: PASS
==================================================================

==================== TEST 2 OUTPUT ====================
{'applicant_name': None, 'amount_ghs': None, 'purpose': None, 'monthly_profit_ghs': None, 'has_collateral_or_guarantor': False, 'repayment_months': None}

TEST 2 EVALUATION: PASS
==================================================================